### ISSUE TITLE
flag provided but not defined: -s

### ISSUE THREAD

**Issue by dockermikeg** [ehazlett/cert-tool#2]
I was trying to use certm to generate Docker client and server keys.  I ran one of the sample commands from the documentation, but I'm getting the following error message:

$ docker run --rm -v $(pwd):/certs ehazlett/certm -d /certs bundle generate -o=local -s localhost -s 127.0.0.1 -s foo.local
Incorrect Usage.

NAME:
   generate - generate new bundle

USAGE:
   command generate [command options] [arguments...]

OPTIONS:
   --host [--host option --host option] SAN/IP SAN for certificate
   --org, -o "unknown"          organization
   --bits, -b "2048"            number of bits in the key (default: 2048)
   --overwrite              overwrite existing certificates and keys

flag provided but not defined: -s
$

**Comment by ehazlett** [comment]
Looks like the docs need updated.  Can you replace "-s" with "--host" and
see if that works?

**Comment by ehazlett** [comment]
@dockermikeg thx for the feedback.  i've fixed the docs and pushed a new release with a few fixes (0.1.2).  Docker pull to get the latest.  I've ran manually through each example and they work with the latest 0.1.2.  Sorry for the inconvenience.

Thanks!
